#################################
# generates calcmig data
# In data :
#For sets of data, set up a package to use lazy-loading of data. 
#
#For objects which are system data, for example lookup tables used in calculations
#within the function, use a file ‘R/sysdata.rda’ in the package sources or create the 
#objects by R code at package installation time. 
#
#
#A sometimes important distinction is that the second approach places 
#objects in the namespace but the first does not. So if it is important
#that the function sees mytable as an object from the package, 
#it is system data and the second approach should be used.

##################################
filecsv<-"C:/Program Files/stacomi/calcmig.csv"
calcmig<-utils::read.csv(filecsv,header=TRUE,sep=";")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(calcmig,internal=FALSE,overwrite=TRUE)



#################################
# generates messages as generated by RefMesssage()
# the message are in the default langage (english)
# from iav three dc with eels
##################################
require(stacomiR)
stacomi(FALSE,FALSE,FALSE)
assign("lang","English",envir=envir_stacomi)	
refMsg=new("RefMsg")
createmessage(refMsg,database_expected=TRUE)
msg=get("msg",envir=envir_stacomi)
devtools::use_data(msg,internal=FALSE,overwrite=TRUE)


#################################
# generates dataset for BilanMigrationMult
# from iav three dc with eels
##################################
require(stacomiR)
stacomi(FALSE,FALSE,FALSE)
bMM_Arzal=new("BilanMigrationMult")
baseODBC<-get("baseODBC",envir=envir_stacomi)
baseODBC[c(2,3)]<-rep("iav",2)
assign("baseODBC",baseODBC,envir_stacomi)
sch<-get("sch",envir=envir_stacomi) # "iav."
assign("sch","iav.",envir_stacomi)
bMM_Arzal=choice_c(bMM_Arzal,
dc=c(5,6,12),
taxons=c("Anguilla anguilla"),
stades=c("AGG","AGJ","CIV"),datedebut="2011-01-01",datefin="2011-12-31")
bMM_Arzal<-charge(bMM_Arzal)
bMM_Arzal<-connect(bMM_Arzal,silent=FALSE)
# to avoid warnings at package checks
bMM_Arzal@dc@data[,"dis_commentaires"]<-iconv(bMM_Arzal@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bMM_Arzal@dc@data[,"type_df"]<-iconv(bMM_Arzal@dc@data[,"type_df"],from="latin1",to="UTF8")
bMM_Arzal@dc@data[,"type_dc"]<-iconv(bMM_Arzal@dc@data[,"type_dc"],from="latin1",to="UTF8")
bMM_Arzal@dc@data[,"dif_localisation"]<-iconv(bMM_Arzal@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bMM_Arzal@taxons@data[,"tax_nom_commun"]<-iconv(bMM_Arzal@taxons@data[,"tax_nom_commun"],from="latin1",to="UTF8")
bMM_Arzal@stades@data[,"std_libelle"]<-iconv(bMM_Arzal@stades@data[,"std_libelle"],from="latin1",to="UTF8")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bMM_Arzal,internal=FALSE,overwrite=TRUE)
bilanOperation<-get("bilanOperation",envir=envir_stacomi)
bilanOperation@data$ope_commentaires<-iconv(bilanOperation@data$ope_commentaires,from="latin1",to="UTF8")
bilanOperation@data$ope_operateur<-iconv(bilanOperation@data$ope_operateur,from="latin1",to="UTF8")
bilanOperation@dc@data[,"dis_commentaires"]<-iconv(bilanOperation@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bilanOperation@dc@data[,"type_df"]<-iconv(bilanOperation@dc@data[,"type_df"],from="latin1",to="UTF8")
bilanOperation@dc@data[,"type_dc"]<-iconv(bilanOperation@dc@data[,"type_dc"],from="latin1",to="UTF8")
bilanOperation@dc@data[,"dif_localisation"]<-iconv(bilanOperation@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
devtools::use_data(bilanOperation,internal=FALSE,overwrite=TRUE)


bilanFonctionnementDF<-get("bilanFonctionnementDF",envir=envir_stacomi)
bilanFonctionnementDF@df@data[,"dis_commentaires"]<-iconv(bilanFonctionnementDF@df@data[,"dis_commentaires"],from="latin1",to="UTF8")
bilanFonctionnementDF@df@data[,"type_df"]<-iconv(bilanFonctionnementDF@df@data[,"type_df"],from="latin1",to="UTF8")
#bilanFonctionnementDF@df@data[,"type_dc"]<-iconv(bilanFonctionnementDF@df@data[,"type_dc"],from="latin1",to="UTF8")
bilanFonctionnementDF@df@data[,"dif_localisation"]<-iconv(bilanFonctionnementDF@df@data[,"dif_localisation"],from="latin1",to="UTF8")
bilanFonctionnementDF@data$per_commentaires<-iconv(bilanFonctionnementDF@data$per_commentaires,from="latin1",to="UTF8")
devtools::use_data(bilanFonctionnementDF,internal=FALSE,overwrite=TRUE)


bilanFonctionnementDC<-get("bilanFonctionnementDC",envir=envir_stacomi)
bilanFonctionnementDC@dc@data[,"dis_commentaires"]<-iconv(bilanFonctionnementDC@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bilanFonctionnementDC@dc@data[,"ouv_libelle"]<-iconv(bilanFonctionnementDC@dc@data[,"ouv_libelle"],from="latin1",to="UTF8")
bilanFonctionnementDC@dc@data[,"type_dc"]<-iconv(bilanFonctionnementDC@dc@data[,"type_dc"],from="latin1",to="UTF8")
bilanFonctionnementDC@dc@data[,"type_df"]<-iconv(bilanFonctionnementDC@dc@data[,"type_df"],from="latin1",to="UTF8")
bilanFonctionnementDC@dc@data[,"dif_localisation"]<-iconv(bilanFonctionnementDC@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bilanFonctionnementDC@data$per_commentaires<-iconv(bilanFonctionnementDC@data$per_commentaires,from="latin1",to="UTF8")

devtools::use_data(bilanFonctionnementDC,internal=FALSE,overwrite=TRUE)
#################################
# generates dataset for BilanMigration
# from the vertical slot fishway located at the estuary of the Vilaine (Brittany)
# Taxa Liza Ramada (Thinlip grey mullet) in 2015
##################################

stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)	
bM_Arzal=new("BilanMigration")
baseODBC<-get("baseODBC",envir=envir_stacomi)
baseODBC[c(2,3)]<-rep("iav",2)
assign("baseODBC",baseODBC,envir_stacomi)
sch<-get("sch",envir=envir_stacomi) # "iav."
assign("sch","iav.",envir_stacomi)
bM_Arzal=choice_c(bM_Arzal,
		dc=5,
		taxons=c("Liza ramada"),
		stades=c("IND"),
		datedebut="2015-01-01",
		datefin="2015-12-31")
bM_Arzal<-charge(bM_Arzal)
bM_Arzal<-connect(bM_Arzal)
bM_Arzal@dc@data[,"dis_commentaires"]<-iconv(bM_Arzal@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"type_df"]<-iconv(bM_Arzal@dc@data[,"type_df"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"type_dc"]<-iconv(bM_Arzal@dc@data[,"type_dc"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"dif_localisation"]<-iconv(bM_Arzal@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bM_Arzal@taxons@data[,"tax_nom_commun"]<-iconv(bM_Arzal@taxons@data[,"tax_nom_commun"],from="latin1",to="UTF8")
bM_Arzal@stades@data[,"std_libelle"]<-iconv(bM_Arzal@stades@data[,"std_libelle"],from="latin1",to="UTF8")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bM_Arzal,internal=FALSE,overwrite=TRUE)



bilanOperation_bM<-get("bilanOperation",envir=envir_stacomi)
bilanOperation_bM@data$ope_commentaires<-iconv(bilanOperation_bM@data$ope_commentaires,from="latin1",to="UTF8")
bilanOperation_bM@data$ope_operateur<-iconv(bilanOperation_bM@data$ope_operateur,from="latin1",to="UTF8")
bilanOperation_bM@dc@data[,"dis_commentaires"]<-iconv(bilanOperation_bM@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bilanOperation_bM@dc@data[,"type_df"]<-iconv(bilanOperation_bM@dc@data[,"type_df"],from="latin1",to="UTF8")
bilanOperation_bM@dc@data[,"type_dc"]<-iconv(bilanOperation_bM@dc@data[,"type_dc"],from="latin1",to="UTF8")
bilanOperation_bM@dc@data[,"dif_localisation"]<-iconv(bilanOperation_bM@dc@data[,"dif_localisation"],from="latin1",to="UTF8")

devtools::use_data(bilanOperation_bM,internal=FALSE,overwrite=TRUE)


bilanFonctionnementDF_bM<-get("bilanFonctionnementDF",envir=envir_stacomi)
bilanFonctionnementDF_bM@df@data[,"dis_commentaires"]<-iconv(bilanFonctionnementDF_bM@df@data[,"dis_commentaires"],from="latin1",to="UTF8")
bilanFonctionnementDF_bM@df@data[,"type_df"]<-iconv(bilanFonctionnementDF_bM@df@data[,"type_df"],from="latin1",to="UTF8")
#bilanFonctionnementDF_bM@df@data[,"type_dc"]<-iconv(bilanFonctionnementDF_bM@df@data[,"type_dc"],from="latin1",to="UTF8")
bilanFonctionnementDF_bM@df@data[,"dif_localisation"]<-iconv(bilanFonctionnementDF_bM@df@data[,"dif_localisation"],from="latin1",to="UTF8")
bilanFonctionnementDF_bM@data$per_commentaires<-iconv(bilanFonctionnementDF_bM@data$per_commentaires,from="latin1",to="UTF8")
devtools::use_data(bilanFonctionnementDF_bM,internal=FALSE,overwrite=TRUE)

bilanFonctionnementDC_bM<-get("bilanFonctionnementDC",envir=envir_stacomi)
bilanFonctionnementDC_bM@dc@data[,"ouv_libelle"]<-iconv(bilanFonctionnementDC_bM@dc@data[,"ouv_libelle"],from="latin1",to="UTF8")
bilanFonctionnementDC_bM@dc@data[,"dis_commentaires"]<-iconv(bilanFonctionnementDC_bM@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bilanFonctionnementDC_bM@dc@data[,"type_dc"]<-iconv(bilanFonctionnementDC_bM@dc@data[,"type_dc"],from="latin1",to="UTF8")
bilanFonctionnementDC_bM@dc@data[,"type_df"]<-iconv(bilanFonctionnementDC_bM@dc@data[,"type_df"],from="latin1",to="UTF8")
bilanFonctionnementDC_bM@dc@data[,"dif_localisation"]<-iconv(bilanFonctionnementDC_bM@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bilanFonctionnementDC_bM@data$per_commentaires<-iconv(bilanFonctionnementDC_bM@data$per_commentaires,from="latin1",to="UTF8")
devtools::use_data(bilanFonctionnementDC_bM,internal=FALSE,overwrite=TRUE)

#################################
# generates dataset for BilanFonctionnementDF
##################################
require(stacomiR)
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
bfDF=new("BilanFonctionnementDF")
bfDF<-choice_c(bfDF,
		1,
		horodatedebut="2015-01-01",
		horodatefin="2015-12-31",
		silent=TRUE)
Sys.setenv(TZ='GMT') # there are data when hour shift, without this the graph will fail
bfDF<-charge(bfDF)
bfDF<-connect(bfDF)

bfDF@df@data[,"dis_commentaires"]<-iconv(bfDF@df@data[,"dis_commentaires"],from="latin1",to="UTF8")
bfDF@df@data[,"type_df"]<-iconv(bfDF@df@data[,"type_df"],from="latin1",to="UTF8")
#bfDF@df@data[,"type_dc"]<-iconv(bfDF@df@data[,"type_dc"],from="latin1",to="UTF8")
bfDF@df@data[,"dif_localisation"]<-iconv(bfDF@df@data[,"dif_localisation"],from="latin1",to="UTF8")
bfDF@data$per_commentaires<-iconv(bfDF@data$per_commentaires,from="latin1",to="UTF8")
#plot(bfDF,plot.type="1")
#plot(bfDF,plot.type="2",title="A nice title")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bfDF,internal=FALSE,overwrite=TRUE)


#################################
# generates dataset for BilanFonctionnementDC
##################################
setwd("F:/workspace/stacomir/pkg/stacomir")
require(stacomiR)
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
bfDC=new("BilanFonctionnementDC")
bfDC<-choice_c(bfDC,
		5,
		horodatedebut="2000-01-01",
		horodatefin="2015-12-31",
		silent=TRUE)
Sys.setenv(TZ='GMT') # there are data when hour shift, without this the graph will fail
bfDC<-charge(bfDC)
bfDC<-connect(bfDC)
bfDC@dc@data[,"ouv_libelle"]<-iconv(bfDC@dc@data[,"ouv_libelle"],from="latin1",to="UTF8")
bfDC@dc@data[,"dis_commentaires"]<-iconv(bfDC@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bfDC@dc@data[,"type_df"]<-iconv(bfDC@dc@data[,"type_df"],from="latin1",to="UTF8")
bfDC@dc@data[,"type_dc"]<-iconv(bfDC@dc@data[,"type_dc"],from="latin1",to="UTF8")
bfDC@dc@data[,"dif_localisation"]<-iconv(bfDC@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bfDC@data$per_commentaires<-iconv(bfDC@data$per_commentaires,from="latin1",to="UTF8")
#plot(bfDC,plot.type="1")
#plot(bfDC,plot.type="2",title="A nice title")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bfDC,internal=FALSE,overwrite=TRUE)

#################################
# generates dataset for Bilan_carlot
##################################
setwd("F:/workspace/stacomir/pkg/stacomir")
require(stacomiR)
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
b_carlot<-new("Bilan_carlot")
# the following will load data for size, 
# parameters  1786 (total size) and C001 (size at video control)
# are all size measures
# dc 5 and 6 are fishways located on the Arzal dam
# two stages are selected
b_carlot<-choice_c(b_carlot,
		dc=c(5,6),
		taxons=c("Anguilla anguilla"),
		stades=c("AGJ","CIV"),
		par=c(1786,"C001"),
		horodatedebut="2013-01-01",
		horodatefin="2013-12-31",
		silent=FALSE)
# two warning produced, ignored if silent=TRUE
b_carlot<-connect(b_carlot)
b_carlot<-calcule(b_carlot)

b_carlot@dc@data[,"ouv_libelle"]<-iconv(b_carlot@dc@data[,"ouv_libelle"],from="latin1",to="UTF8")
b_carlot@dc@data[,"dis_commentaires"]<-iconv(b_carlot@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
b_carlot@dc@data[,"type_df"]<-iconv(b_carlot@dc@data[,"type_df"],from="latin1",to="UTF8")
b_carlot@dc@data[,"type_dc"]<-iconv(b_carlot@dc@data[,"type_dc"],from="latin1",to="UTF8")
b_carlot@dc@data[,"dif_localisation"]<-iconv(b_carlot@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
b_carlot@par@data[,"par_nom"]<-iconv(b_carlot@par@data[,"par_nom"],from="latin1",to="UTF8")
b_carlot@data$dev_libelle<-iconv(b_carlot@data$dev_libelle,from="latin1",to="UTF8")
b_carlot@data$std_libelle<-iconv(b_carlot@data$std_libelle,from="latin1",to="UTF8")
b_carlot@data$val_libelle<-iconv(b_carlot@data$val_libelle,from="latin1",to="UTF8")
b_carlot@data$par_nom<-iconv(b_carlot@data$par_nom,from="latin1",to="UTF8")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(b_carlot,internal=FALSE,overwrite=TRUE)

#################################
# generates dataset for BilanMigrationInterAnnuelle
##################################
setwd("F:/workspace/stacomir/pkg/stacomir")
require(stacomiR)
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
require(stacomiR)
stacomi(gr_interface=FALSE,login_window=FALSE,database_expected=FALSE)

baseODBC<-get("baseODBC",envir=envir_stacomi)
baseODBC[c(2,3)]<-rep("pmp",2)
assign("baseODBC",baseODBC,envir_stacomi)
sch<-get("sch",envir=envir_stacomi)
assign("sch","pmp.",envir_stacomi)
bmi<-new("BilanMigrationInterAnnuelle")

bmi<-choice_c(bmi,
		dc=16,
		taxons=c("Anguilla anguilla"),
		stades=c("AGJ"),
		anneedebut=1984,
		anneefin=2015,
		silent=TRUE)
bmi<-connect(bmi,silent=TRUE)	


bmi@dc@data[,"ouv_libelle"]<-iconv(bmi@dc@data[,"ouv_libelle"],from="latin1",to="UTF8")
bmi@dc@data[,"dis_commentaires"]<-iconv(bmi@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bmi@dc@data[,"type_df"]<-iconv(bmi@dc@data[,"type_df"],from="latin1",to="UTF8")
bmi@dc@data[,"type_dc"]<-iconv(bmi@dc@data[,"type_dc"],from="latin1",to="UTF8")
bmi@dc@data[,"dif_localisation"]<-iconv(bmi@dc@data[,"dif_localisation"],from="latin1",to="UTF8")

setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bmi,internal=FALSE,overwrite=TRUE)



