#################################
# generates calcmig data
# In data :
#For sets of data, set up a package to use lazy-loading of data. 
#
#For objects which are system data, for example lookup tables used in calculations
#within the function, use a file ‘R/sysdata.rda’ in the package sources or create the 
#objects by R code at package installation time. 
#
#
#A sometimes important distinction is that the second approach places 
#objects in the namespace but the first does not. So if it is important
#that the function sees mytable as an object from the package, 
#it is system data and the second approach should be used.

##################################
filecsv<-"C:/Program Files/stacomi/calcmig.csv"
calcmig<-utils::read.csv(filecsv,header=TRUE,sep=";")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(calcmig,internal=FALSE,overwrite=TRUE)



#################################
# generates messages as generated by RefMesssage()
# the message are in the default langage (english)
# from iav three dc with eels
##################################
require(stacomiR)
stacomi(FALSE,FALSE,FALSE)
assign("lang","English",envir=envir_stacomi)	
refMsg=new("RefMsg")
createmessage(refMsg,database_expected=TRUE)
msg=get("msg",envir=envir_stacomi)
devtools::use_data(msg,internal=FALSE,overwrite=TRUE)


#################################
# generates dataset for BilanMigrationMult
# from iav three dc with eels
##################################
require(stacomiR)
stacomi(FALSE,FALSE,FALSE)
bM_Arzal=new("BilanMigrationMult")
bM_Arzal=choice_c(bM_Arzal,
dc=c(5,6,12),
taxons=c("Anguilla anguilla"),
stades=c("AGG","AGJ","CIV"),datedebut="2011-01-01",datefin="2011-12-31")
bM_Arzal<-charge(bM_Arzal)
bM_Arzal<-connect(bM_Arzal,silent=FALSE)
# to avoid warnings at package checks
bM_Arzal@dc@data[,"dis_commentaires"]<-iconv(bM_Arzal@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"type_df"]<-iconv(bM_Arzal@dc@data[,"type_df"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"type_dc"]<-iconv(bM_Arzal@dc@data[,"type_dc"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"dif_localisation"]<-iconv(bM_Arzal@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bM_Arzal@taxons@data[,"tax_nom_commun"]<-iconv(bM_Arzal@taxons@data[,"tax_nom_commun"],from="latin1",to="UTF8")
bM_Arzal@stades@data[,"std_libelle"]<-iconv(bM_Arzal@stades@data[,"std_libelle"],from="latin1",to="UTF8")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bM_Arzal,internal=FALSE,overwrite=TRUE)
bilanOperation<-get("bilanOperation",envir=envir_stacomi)
devtools::use_data(bilanOperation,internal=FALSE,overwrite=TRUE)
bilanFonctionnementDF<-get("bilanFonctionnementDF",envir=envir_stacomi)
devtools::use_data(bilanFonctionnementDF,internal=FALSE,overwrite=TRUE)
bilanFonctionnementDC<-get("bilanFonctionnementDC",envir=envir_stacomi)
devtools::use_data(bilanFonctionnementDC,internal=FALSE,overwrite=TRUE)
#################################
# generates dataset for BilanMigration
# from the vertical slot fishway located at the estuary of the Vilaine (Brittany)
# Taxa Liza Ramada (Thinlip grey mullet) in 2015
##################################

stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)	
bM_Arzal=new("BilanMigration")
bM_Arzal=choice_c(bM_Arzal,
		dc=5,
		taxons=c("Liza ramada"),
		stades=c("IND"),
		datedebut="2015-01-01",
		datefin="2015-12-31")
bM_Arzal<-connect(bM_Arzal)
bM_Arzal@dc@data[,"dis_commentaires"]<-iconv(bM_Arzal@dc@data[,"dis_commentaires"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"type_df"]<-iconv(bM_Arzal@dc@data[,"type_df"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"type_dc"]<-iconv(bM_Arzal@dc@data[,"type_dc"],from="latin1",to="UTF8")
bM_Arzal@dc@data[,"dif_localisation"]<-iconv(bM_Arzal@dc@data[,"dif_localisation"],from="latin1",to="UTF8")
bM_Arzal@taxons@data[,"tax_nom_commun"]<-iconv(bM_Arzal@taxons@data[,"tax_nom_commun"],from="latin1",to="UTF8")
bM_Arzal@stades@data[,"std_libelle"]<-iconv(bM_Arzal@stades@data[,"std_libelle"],from="latin1",to="UTF8")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bM_Arzal,internal=FALSE,overwrite=TRUE)



#################################
# generates dataset for BilanFonctionnementDF
##################################
require(stacomiR)
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
bfDF=new("BilanFonctionnementDF")
bfDF<-choice_c(bfDF,
		1,
		horodatedebut="2015-01-01",
		horodatefin="2015-12-31",
		silent=TRUE)
Sys.setenv(TZ='GMT') # there are data when hour shift, without this the graph will fail
bfDF<-charge(bfDF)
bfDF<-connect(bfDF)
#plot(bfDF,plot.type="1")
#plot(bfDF,plot.type="2",title="A nice title")
setwd("F:/workspace/stacomir/pkg/stacomir")
devtools::use_data(bfDF,internal=FALSE,overwrite=TRUE)