#################################
# generates messages as generated by RefMesssage()
# the message are in the default langage (english)
# from iav three dc with eels
##################################
source ("F:/workspace/stacomir/pkg/stacomir/inst/config/stacomi_manual_launch.r")
assign("lang","English",envir=envir_stacomi)	
refMsg=new("RefMsg")
createmessage(refMsg,pre_launch_test=TRUE)
msg=get("msg",envir=envir_stacomi)
devtools::use_data(msg,internal=FALSE,overwrite=TRUE)


#################################
# generates dataset for BilanMigrationMult
# from iav three dc with eels
##################################
require(stacomiR)
require(RODBC)
stacomi(FALSE)
bMM_Arzal=new("BilanMigrationMult")
bMM_Arzal=load(bMM_Arzal,
dc=c(5,6,12),
taxons=c("Anguilla anguilla"),
stades=c("AGG","AGJ","CIV"),datedebut="2011-01-01",datefin="2011-12-31")
bMM_Arzal<-connect(bMM_Arzal)
devtools::use_data(bMM_Arzal,internal=FALSE,overwrite=TRUE)