context("BilanMigrationCar")


test_that("test creating an instance of BilanMigrationCar and connect method (logrami required)",{
			require(stacomiR)
			stacomi(gr_interface=FALSE,login_window=FALSE,database_expected=TRUE)
			# overriding user schema to point to logrami
			assign("sch","logrami.",envir_stacomi)
			bmC<-new("BilanMigrationCar")
			baseODBC<-get("baseODBC",envir=envir_stacomi)
			baseODBC[c(2,3)]<-rep("logrami",2)
			assign("baseODBC",baseODBC,envir_stacomi)
			sch<-get("sch",envir=envir_stacomi)
			assign("sch","logrami.",envir_stacomi)
# here parqual is not in the list
# so this is equivalent to parqual=NULL
			bmC<-choice_c(bmC,
					dc=c(107,108,101),
					taxons=c("Salmo salar"),
					stades=c('5','11','BEC','BER','IND'),
					parquan=c('A124','C001'),
					parqual=NULL,
					horodatedebut="2009-01-01",
					horodatefin="2012-12-31",
					silent=TRUE)
# bmC<-charge(bmC) not necessary there
			bmC<-connect(bmC)
			expect_true(is.null(bmC@data$parqual),label="there should be no data in parqual when not qualitative parm are selected")
			expect_true(nrow(bmC@data$parquan)>0,"There should be data in the parquan slot when quantitative parm are selected" )
			rm("envir_stacomi",envir =.GlobalEnv)
		})

test_that("test setasqualitative method",{
			require(stacomiR)
			stacomi(gr_interface=FALSE,login_window=FALSE,database_expected=TRUE)
			# overriding user schema to point to iav
			assign("sch","logrami.",envir_stacomi)
			bmC<-new("BilanMigrationCar")
			baseODBC<-get("baseODBC",envir=envir_stacomi)
			baseODBC[c(2,3)]<-rep("logrami",2)
			assign("baseODBC",baseODBC,envir_stacomi)
			sch<-get("sch",envir=envir_stacomi)
			assign("sch","logrami.",envir_stacomi)
# here parqual is not in the list
# so this is equivalent to parqual=NULL
			bmC<-choice_c(bmC,
					dc=c(107,108,101),
					taxons=c("Salmo salar"),
					stades=c('5','11','BEC','BER','IND'),
					parquan=c('A124','C001'),
					parqual=NULL,
					horodatedebut="2009-01-01",
					horodatefin="2012-12-31",
					silent=TRUE)
# bmC<-charge(bmC) not necessary there
			bmC<-connect(bmC,silent=TRUE)
# load the dataset generated by previous lines
			bmC<-setasqualitative(bmC,
					par='A124',
					silent=TRUE,
					breaks=c(0,1.5,2.5,10),
					label=c("age 1","age 2","age 3"))
			expect_true(bmC@parqual@par_selectionne=='A124', label="Test passing quant parm A124 to qualitative failed")
			expect_false(bmC@parquan@par_selectionne=='A124', label="The parameter A124 should have been removed from quant parm")
			expect_true('A124'%in%bmC@data$parqual$car_par_code)
			expect_false('A124'%in%bmC@data$parquan$car_par_code)
			rm("envir_stacomi",envir =.GlobalEnv)
		})


test_that("test calcule method",{
			require(stacomiR)
			stacomi(gr_interface=FALSE,login_window=FALSE,database_expected=TRUE)
			# overriding user schema to point to iav
			assign("sch","logrami.",envir_stacomi)
			bmC<-new("BilanMigrationCar")
			baseODBC<-get("baseODBC",envir=envir_stacomi)
			baseODBC[c(2,3)]<-rep("logrami",2)
			assign("baseODBC",baseODBC,envir_stacomi)
			sch<-get("sch",envir=envir_stacomi)
			assign("sch","logrami.",envir_stacomi)
			bmC<-choice_c(bmC,
					dc=c(107,108,101),
					taxons=c("Salmo salar"),
					stades=c('5','11','BEC','BER','IND'),
					parquan=c('A124','C001'),
					parqual=NULL,
					horodatedebut="2012-01-01",
					horodatefin="2012-12-31",
					silent=TRUE)
			bmC<-connect(bmC)
			bmC<-calcule(bmC,silent=TRUE)
			expect_true(nrow(bmC@calcdata)>0, label="Test that calcule method worked")
			expect_true(all(is.na(bmC@calcdata$car_par_code_qual)), label="Test that calcule method does not return any qualitative result in absence of qualitative parm")
			
			# now with a qualitative parm
			bmC<-setasqualitative(bmC,
					par='A124',
					silent=TRUE,breaks=c(0,1.5,2.5,10),label=c("age 1","age 2","age 3"))
			bmC<-calcule(bmC,silent=TRUE)
			expect_true(any(!is.na(bmC@calcdata$car_par_code_qual))&any(!is.na(bmC@calcdata$car_par_code_quan)), label="The merge function works and returns both qualitative and quantitative parameters")
			
			rm("envir_stacomi",envir =.GlobalEnv)
		})


