require(stacomiR)
# launching stacomi without selecting the scheme or interface
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
# the following script will load the Arzal dataset if connected to iav schema
\dontrun{
	#create an instance of the class
	b_carlot<-new("Bilan_carlot")
	# the following will load data for size, 
	# parameters 1786 (total size) C001 (size at video control)
	# dc 5 and 6 are fishways located on the Arzal dam
	# two stages are selected
	b_carlot<-choice_c(b_carlot,
			dc=c(5,6),
			taxons=c("Anguilla anguilla"),
			stades=c("AGJ","CIV"),
			par=c(1785,1786,1787,"C001"),
			horodatedebut="2013-01-01",
			horodatefin="2013-12-31",
			silent=FALSE)
	# two warning produced, ignored if silent=TRUE
	b_carlot<-connect(b_carlot)
	b_carlot<-calcule(b_carlot,silent=TRUE)
	
}	
# load the dataset generated by previous lines
data("b_carlot")

# A "violin" plot
plot(b_carlot,plot.type="1",silent=TRUE)
# get the plot from envir_stacomi to change labels for name
# if you use require(ggplot2) the :: argument is not needed
# e.g. write require(ggplot2);g<-get("g",envir=envir_stacomi)
# g+xlab("size")+ylab("year")
if (requireNamespace("ggplot2", quietly = TRUE)){
	g<-get("g",envir=envir_stacomi)
	g+ggplot2::xlab("size")+ggplot2::ylab("year")
}
# A boxplot per month
plot(b_carlot,plot.type="2",silent=TRUE)
# A xyplot
plot(b_carlot,plot.type="3",silent=TRUE)

\dontrun{

#####################################
# an example graph created manually from data
#####################################
# two variables one on DC, one on stage
# passing dc information to the stage variable
b_carlot@data$std_libelle[b_carlot@data$ope_dic_identifiant==5]<-"Yellow eel (vert. slot fishway)"
b_carlot@data$std_libelle[b_carlot@data$std_libelle=="Anguille jaune"]<-"Yellow eel (ramp)"
b_carlot@data$std_libelle[b_carlot@data$std_libelle=="civelle"]<-"Glass eel (ramp)"
# creating a boxplot with custom output : an example
# again if you use require(ggplot2) the :: argument is not needed

if (requireNamespace("ggplot2", quietly = TRUE)){
	g<-ggplot2::ggplot(b_carlot@data)+
			ggplot2::geom_boxplot(ggplot2::aes(x=annee,
							y =car_valeur_quantitatif,
							fill = std_libelle))+		
			ggplot2::xlab("size")+ggplot2::ylab("year")+
			ggplot2::scale_fill_manual("stage & fishway",
					values=c("Yellow eel (vert. slot fishway)"="blue",
							"Yellow eel (ramp)"="turquoise3",
							"Glass eel (ramp)"="Cyan"))+
			ggplot2::theme_bw()
	print(g)
}

# get a simple summary using Hmisc::describe

summary(b_carlot)
# get the command line to create the object using choice_c 
# when the graphical interface has been used
print(b_carlot)
}
