require(stacomiR)
# launching stacomi without selecting the scheme or interface
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=TRUE)
# the following script will load data from the two Anguillere monitored in the Somme

\dontrun{
	#create an instance of the class
	bilan_adm<-new("BilanAgedemer")
	baseODBC<-get("baseODBC",envir=envir_stacomi)
	baseODBC[c(2,3)]<-rep("logrami",2)
	assign("baseODBC",baseODBC,envir_stacomi)
	sch<-get("sch",envir=envir_stacomi)
	assign("sch","logrami.",envir_stacomi)
	bilan_adm<-choice_c(bilan_adm,
			dc=c(107,108,101),			
			horodatedebut="2012-01-01",
			horodatefin="2012-12-31",
			limit1hm=675,
			limit2hm=875,
			silent=FALSE
			)
	bilan_adm<-connect(bilan_adm)
	
}	
# load the dataset generated by previous lines
data("bilan_adm")
# the calculation will fill the slot calcdata
bilan_adm<-calcule(bilan_adm)
# stages are in bilan_adm@calcdata[["6"]][,"stage"] 
#look at data structure using str(bilan_adm@calcdata[["6"]])

# standard plot as drawn by Laurent Beaulaton (Analyse des données d'argenture acquises en France)
# showing Durif's stage according to size and eye diameter
plot(bilan_adm, plot.type=1)


# print a summary statistic, and save the output in a list for later use
stats<-summary(bilan_adm)

object=new("RefMsg")
msgfr<-charge_avec_filtre(object,lang='French')
str(msgfr)