require(stacomiR)
# launching stacomi without selecting the scheme or interface
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=TRUE)
# the following script will load data from the two Anguillere monitored in the Somme

\dontrun{
	#create an instance of the class
	bilPM<-new("Bilan_poids_moyen")
	baseODBC<-get("baseODBC",envir=envir_stacomi)
	baseODBC[c(2,3)]<-rep("iav",2)
	assign("baseODBC",baseODBC,envir_stacomi)
	sch<-get("sch",envir=envir_stacomi)
	assign("sch","iav.",envir_stacomi)
	bilPM@liste<-charge(object=bilPM@liste,listechoice=c("=1",">1","tous"),label="")
	# here I'm using weights when number are larger than 1 ie wet weight
	bilPM<-choice_c(bilPM,
			dc=c(6),			
			anneedebut="2009",
			anneefin="2015",
			selectedvalue=">1",
			silent=FALSE)
	bilPM<-connect(bilPM)	
}	
# load the dataset generated by previous lines
data("bilPM")
# the calculation will fill the slot calcdata
bilPM<-calcule(bilPM)

plot(bilPM, plot.type=1)

#
plot(bilPM, plot.type=2)

# plot showing fulton's coefficient, and size weight graphs
# inspired from Acou et al., 2009 
# Differential Production and Condition Indices of Premigrant
# Eels in Two Small Atlantic Coastal Catchments
# of France
plot(bilPM, plot.type=3)
# get a list of summary data and print output to screen

plot(bilPM, plot.type=4)
