require(stacomiR)
# launching stacomi without selecting the scheme or interface
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
# the following script will load data from the two Anguillère monitored in the Sommes
\dontrun{
	#create an instance of the class
	bilanArg<-new("BilanArgentee")
	baseODBC<-get("baseODBC",envir=envir_stacomi)
	baseODBC[c(2,3)]<-rep("fd80",2)
	assign("baseODBC",baseODBC,envir_stacomi)
	sch<-get("sch",envir=envir_stacomi)
	assign("sch","fd80.",envir_stacomi)
	bilanArg<-choice_c(bilanArg,
			dc=c(2,6),			
			horodatedebut="2010-09-01",
			horodatefin="2016-10-04",
			silent=FALSE)
	bilanArg<-connect(bilanArg)
	
}	
# load the dataset generated by previous lines
data("bilanArg")
# the calculation will fill the slot calcdata
bilanArg<-calcule(bilanArg)
# stages are in bilanArg@calcdata[["6"]][,"stage"] look at data structure using str(bilanArg@calcdata[["6"]])
plot(bilanArg, plot.type=1)