require(stacomiR)
# launching stacomi without selecting the scheme or interface
stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)
\dontrun{
	#create an instance of the class
	bilPM<-new("Bilan_poids_moyen")
	baseODBC<-get("baseODBC",envir=envir_stacomi)
	baseODBC[c(2,3)]<-rep("iav",2)
	assign("baseODBC",baseODBC,envir_stacomi)
	sch<-get("sch",envir=envir_stacomi)
	assign("sch","iav.",envir_stacomi)
	bilPM@liste<-charge(object=bilPM@liste,listechoice=c("=1",">1","tous"),label="")
	# here I'm using weights when number are larger than 1 ie wet weight
	# always choose a date from one year to the next eg 2010 to 2011
	# as the dates are from august to august
	bilPM<-choice_c(bilPM,
			dc=c(6),			
			anneedebut="2009",
			anneefin="2015",
			selectedvalue=">1",
			silent=FALSE)
	bilPM<-connect(bilPM)	
}	
# load the dataset generated by previous lines
data("bilPM")
# the calculation will fill the slot calcdata
bilPM<-calcule(bilPM)
# A ggplot showing the trend in weight
plot(bilPM, plot.type=1)
# A plot showing both the data and the trend as recorded in the database
plot(bilPM, plot.type=2)
# Same as plot.type=1 but with size according to size of the sample,
# usefull for wet weights where weight are recorded on a number of glass eel
plot(bilPM, plot.type=3)
# First model with nls, see Guerault and Desaunay (1993) 
model(bilPM,model.type="seasonal")
model(bilPM,model.type="seasonal1")
