require(stacomiR)

stacomi(gr_interface=FALSE,
		login_window=FALSE,
		database_expected=FALSE)

\dontrun{
	bmC<-new("BilanMigrationCar")
	baseODBC<-get("baseODBC",envir=envir_stacomi)
	baseODBC[c(2,3)]<-rep("logrami",2)
	assign("baseODBC",baseODBC,envir_stacomi)
	sch<-get("sch",envir=envir_stacomi)
	assign("sch","logrami.",envir_stacomi)
	# here parqual is not in the list
	# so this is equivalent to parqual=NULL
	bmC<-choice_c(bmC,
			dc=c(107,108,101),
			taxons=c("Salmo salar"),
			stades=c('5','11','BEC','BER','IND'),
			parquan=c('A124','C001','1786','1785'),
			horodatedebut="2012-01-01",
			horodatefin="2012-12-31",
			silent=FALSE)
	# bmC<-charge(bmC) not necessary there
	bmC<-connect(bmC)
	
}	
# load the dataset generated by previous lines
data("bmC")
# age will be plotted as a qualitative variable
bmC<-setasqualitative(bmC,par='A124',breaks=c(0,1.5,2.5,10),label=c("age 1","age 2","age 3"))
bmC<-calcule(bmC,silent=TRUE)
plot(bmC,plot.type="quant",silent=TRUE)
# one quantitative parameter found, manual choice of color
plot(bmC,plot.type="quant",color_parm=c("C001"="red"),silent=TRUE)
plot(bmC,plot.type="qual",silent=TRUE)
plot(bmC,plot.type="crossed")
plot(bmC,plot.type="crossed",color_parm=c("age 1"="#379ec6","age 2"="#173957","age 3"="#b09953"))
xt<-xtable(bmC)
# use method print.xtable to get the output
\dontrun{
# An example with several years
bmC<-new("BilanMigrationCar")
baseODBC<-get("baseODBC",envir=envir_stacomi)
baseODBC[c(2,3)]<-rep("logrami",2)
assign("baseODBC",baseODBC,envir_stacomi)
sch<-get("sch",envir=envir_stacomi)
assign("sch","logrami.",envir_stacomi)
# here parqual is not in the list
# so this is equivalent to parqual=NULL
bmC<-choice_c(bmC,
		dc=c(107,108,101),
		taxons=c("Salmo salar"),
		stades=c('5','11','BEC','BER','IND'),
		parquan=c('A124','C001','1786','1785'),
		horodatedebut="2009-01-01",
		horodatefin="2012-12-31",
		silent=FALSE)
# bmC<-charge(bmC) not necessary there
bmC<-connect(bmC)
# load the dataset generated by previous lines
bmC<-setasqualitative(bmC,par='A124',breaks=c(0,1.5,2.5,10),label=c("age 1","age 2","age 3"))
bmC<-calcule(bmC,silent=TRUE)

}

