#' function to print and save statistics in .csv and .html formats for BilanMigration and BilanMigrationMult class
#' @param tableau A table with the following columns : No.pas,debut_pas,fin_pas,              
#' ope_dic_identifiant,lot_tax_code,lot_std_code,type_de_quantite,MESURE,CALCULE,               
#' EXPERT,PONCTUEL,Effectif_total,taux_d_echappement,coe_valeur_coefficient
#' @note this function is intended to be called from within the summary method 
#' @param time.sequence Passed from BilanMigration or BilanMigrationMult
#' @param taxon  Taxa
#' @param stade The Stage
#' @param DC  The counting device
#' @param resum A summary table generated by funstat
#' @param silent If TRUE, all messages turned off (except warnings and errors) 
#' @author Cedric Briand \email{cedric.briand"at"eptb-vilaine.fr}
funtable=function(tableau,time.sequence,taxon,stade,DC,resum,silent){
	annee=paste(unique(strftime(as.POSIXlt(time.sequence),"%Y")),collapse=",")
	tableau$debut_pas<-as.character(tableau$debut_pas)
	path1=file.path(path.expand(get("datawd",envir=envir_stacomi)),paste(DC,"_",taxon,"_",stade,"_",annee,".csv",sep=""),fsep ="/")
	write.table(tableau,file=path1,row.names=FALSE,col.names=TRUE,sep=";")
	if (!silent) funout(gettextf("writing of %s\n",path1))
	path1html=file.path(path.expand(get("datawd",envir=envir_stacomi)),paste(DC,"_",taxon,"_",stade,"_",annee,".html",sep=""),fsep ="/")
	funhtml(data=tableau,
			caption=paste(DC,"_",taxon,"_",stade,"_",annee,".csv",sep=""),
			top=TRUE,
			outfile=path1html,
			clipboard=FALSE,
			append=FALSE,
			digits=2
	)
	if (!silent) funout(gettextf("writing of %s\n",path1html))
	if( !is.null(resum) )
	{
		path2=file.path(path.expand(get("datawd",envir=envir_stacomi)),paste("res",DC,"_",taxon,"_",stade,"_",annee,".csv",sep=""),fsep ="/")
		write.table(resum,path2,row.names=TRUE,col.names=TRUE,sep=";")
		path2html=file.path(path.expand(get("datawd",envir=envir_stacomi)),paste("res",annee,".html",sep=""),fsep ="/")
		if (!silent) funout(gettextf("writing of %s\n",path2))
		funhtml(data=resum,
				caption=paste("Sommes mensuelles",annee),
				top=TRUE,
				outfile=path2html,
				clipboard=FALSE,
				append=TRUE,
				digits=2
		)
		if (!silent) funout(gettextf("writing of %s\n",path2html))
	}
}


